AVALIABLE_SERVICES = ['acm', 'acm-pca', 'alexaforbusiness', 'apigateway', 'application-autoscaling', 'appstream',
                      'appsync', 'athena', 'autoscaling', 'autoscaling-plans', 'batch', 'budgets', 'ce', 'cloud9',
                      'clouddirectory', 'cloudformation', 'cloudfront', 'cloudhsm', 'cloudhsmv2', 'cloudsearch',
                      'cloudsearchdomain', 'cloudtrail', 'cloudwatch', 'codebuild', 'codecommit', 'codedeploy',
                      'codepipeline', 'codestar', 'cognito-identity', 'cognito-idp', 'cognito-sync', 'comprehend',
                      'config', 'connect', 'cur', 'datapipeline', 'dax', 'devicefarm', 'directconnect', 'discovery',
                      'dms', 'ds', 'dynamodb', 'dynamodbstreams', 'ec2', 'ecr', 'ecs', 'efs', 'elasticache',
                      'elasticbeanstalk', 'elastictranscoder', 'elb', 'elbv2', 'emr', 'es', 'events', 'firehose', 'fms',
                      'gamelift', 'glacier', 'glue', 'greengrass', 'guardduty', 'health', 'iam', 'importexport',
                      'inspector', 'iot', 'iot-data', 'iot-jobs-data', 'iot1click-devices', 'iot1click-projects',
                      'iotanalytics', 'kinesis', 'kinesis-video-archived-media', 'kinesis-video-media',
                      'kinesisanalytics', 'kinesisvideo', 'kms', 'lambda', 'lex-models', 'lex-runtime', 'lightsail',
                      'logs', 'machinelearning', 'marketplace-entitlement', 'marketplacecommerceanalytics',
                      'mediaconvert', 'medialive', 'mediapackage', 'mediastore', 'mediastore-data',
                      'meteringmarketplace', 'mgh', 'mobile', 'mq', 'mturk', 'opsworks', 'opsworkscm', 'organizations',
                      'pinpoint', 'polly', 'pricing', 'rds', 'redshift', 'rekognition', 'resource-groups',
                      'resourcegroupstaggingapi', 'route53', 'route53domains', 's3', 'sagemaker', 'sagemaker-runtime',
                      'sdb', 'secretsmanager', 'serverlessrepo', 'servicecatalog', 'servicediscovery', 'ses', 'shield',
                      'sms', 'snowball', 'sns', 'sqs', 'ssm', 'stepfunctions', 'storagegateway', 'sts', 'support',
                      'swf', 'transcribe', 'translate', 'waf', 'waf-regional', 'workdocs', 'workmail', 'workspaces',
                      'xray']

DYNAMODB_OPERATIONS = ['batch_get_item', 'batch_write_item', 'can_paginate', 'create_backup', 'create_global_table',
                       'create_table', 'delete_backup', 'delete_item', 'delete_table', 'describe_backup',
                       'describe_continuous_backups', 'describe_global_table', 'describe_global_table_settings',
                       'describe_limits', 'describe_table', 'describe_time_to_live', 'generate_presigned_url',
                       'get_item', 'get_paginator', 'get_waiter', 'list_backups', 'list_global_tables', 'list_tables',
                       'list_tags_of_resource', 'put_item', 'query', 'restore_table_from_backup',
                       'restore_table_to_point_in_time', 'scan', 'tag_resource', 'untag_resource',
                       'update_continuous_backups', 'update_global_table', 'update_global_table_settings',
                       'update_item', 'update_table', 'update_time_to_live']
